# Generated by Django 6.0.4 on 2026-04-08 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0002_rename_data_publicacao_noticia_data_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentario',
            options={'ordering': ['-data_criacao']},
        ),
        migrations.RenameField(
            model_name='comentario',
            old_name='data',
            new_name='data_criacao',
        ),
        migrations.AddField(
            model_name='comentario',
            name='autor',
            field=models.CharField(default='Anônimo', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comentario',
            name='noticia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='noticias.noticia'),
        ),
    ]
